apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mongo
spec:
  selector:
    matchLabels:
      app: api-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: api-mongo
    spec:
      containers:
      - name: api-mongo
        image: zero101010/monprospecteur:4fb468e21110533b711e0ef6e78d5922962bf761
        ports:
        - containerPort: 3000