apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.devopstests.com
    secretName: echo-tls
  rules:
  - host: api.devopstests.com
    http:
      paths:
      - backend:
          serviceName: api-mongo
          servicePort: 80