name: Node.js CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}