name: Node.js CI

on: [push]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        cp .env.example .env
        npm install
        ls
    - name: Docker push
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        IMAGE: zero101010/monprospecteur
      run: |
        ls
        docker login -u zero101010 -p $DOCKER_PASSWORD
        docker build -t $IMAGE:$GITHUB_SHA .
        docker push $IMAGE:$GITHUB_SHA